"""Generate the English pre-recorded clips for the Widushi learning app.

Uses Piper TTS with the `en_US-lessac-medium` voice. Ensures the
`.onnx` + `.onnx.json` files are present in `<WORKDIR>/models/`
(downloading from HuggingFace `rhasspy/piper-voices` if missing) and
synthesises each clip into `<WORKDIR>/clips/en/<clip_id>.wav` at
22050 Hz mono.

Hindi clips are generated by a separate, higher-quality pipeline
(`generate_clips_hi.py`, Indic-Parler-TTS) because Piper Hindi is
phonemizer-bound and sounds noticeably non-native.

Idempotent: skips clips whose `.wav` already exists. Designed as the
entrypoint of the `piper-clips` Docker image but also runnable on the
host (set `WORKDIR` or run it from `pre-generated-clips/`).
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import urllib.request
import wave
from pathlib import Path

# (clip_id, english_text) — copied verbatim from phases/1.md.
CLIPS: list[tuple[str, str]] = [
    ("ack_okay", "Okay"),
    ("ack_got_it", "Got it"),
    ("ack_on_it", "On it"),
    ("ack_sure", "Sure"),
    ("greet_hello", "Hello"),
    ("greet_hi", "Hi there"),
    ("wait_moment", "One moment"),
    ("wait_thinking", "Let me think"),
    ("wait_checking", "Let me check"),
    ("done_here", "Here you go"),
    ("done_set", "All set"),
    ("error_repeat", "Sorry, could you say that again?"),
    ("error_unclear", "I didn't quite catch that"),
    ("error_unknown", "I'm not sure about that"),
    ("listen_start", "I'm listening"),
    ("thanks", "Thank you"),
]

VOICE = "en_US-lessac-medium"

_HF_BASE = "https://huggingface.co/rhasspy/piper-voices/resolve/main"
VOICE_URL = f"{_HF_BASE}/en/en_US/lessac/medium"

EXPECTED_SAMPLE_RATE = 22050
EXPECTED_CHANNELS = 1


def _log(msg: str) -> None:
    print(msg, flush=True)


def _download(url: str, dest: Path) -> None:
    """Download `url` to `dest` atomically (write to .part, then rename)."""
    tmp = dest.with_suffix(dest.suffix + ".part")
    _log(f"[dl]   {url} -> {dest}")
    with urllib.request.urlopen(url) as resp, tmp.open("wb") as f:
        shutil.copyfileobj(resp, f)
    tmp.replace(dest)


def ensure_model(name: str, base_url: str, models_dir: Path) -> Path:
    """Make sure both `<name>.onnx` and `<name>.onnx.json` exist in
    `models_dir`. Returns the path to the `.onnx` file."""
    models_dir.mkdir(parents=True, exist_ok=True)
    for suffix in (".onnx", ".onnx.json"):
        target = models_dir / f"{name}{suffix}"
        if target.exists() and target.stat().st_size > 0:
            continue
        _download(f"{base_url}/{name}{suffix}", target)
    return models_dir / f"{name}.onnx"


def synth(text: str, model_path: Path, out_path: Path) -> None:
    """Synthesise `text` to `out_path` (22050 Hz mono wav) using Piper."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "piper",
        "--model", str(model_path),
        "--output_file", str(out_path),
    ]
    proc = subprocess.run(
        cmd,
        input=text.encode("utf-8"),
        capture_output=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr.decode("utf-8", errors="replace"))
        raise RuntimeError(
            f"piper failed (exit {proc.returncode}) for text {text!r}"
        )


def validate_wav(path: Path) -> None:
    """Confirm the produced wav matches the spec: 22050 Hz mono."""
    with wave.open(str(path), "rb") as w:
        sr = w.getframerate()
        ch = w.getnchannels()
        frames = w.getnframes()
    if sr != EXPECTED_SAMPLE_RATE or ch != EXPECTED_CHANNELS:
        raise RuntimeError(
            f"{path}: expected {EXPECTED_SAMPLE_RATE} Hz mono, "
            f"got {sr} Hz / {ch} ch"
        )
    if frames == 0:
        raise RuntimeError(f"{path}: empty wav (0 frames)")


def main() -> int:
    workdir = Path(os.environ.get("WORKDIR", "/work")).resolve()
    models_dir = workdir / "models"
    out_dir = workdir / "clips" / "en"
    _log(f"workdir     = {workdir}")
    _log(f"models_dir  = {models_dir}")
    _log(f"out_dir     = {out_dir}")

    model_path = ensure_model(VOICE, VOICE_URL, models_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    generated = 0
    skipped = 0
    for clip_id, text in CLIPS:
        wav_path = out_dir / f"{clip_id}.wav"
        rel = wav_path.relative_to(workdir)
        if wav_path.exists() and wav_path.stat().st_size > 0:
            _log(f"[skip] {rel}")
            skipped += 1
            continue
        _log(f"[gen]  {rel} :: {text!r}")
        synth(text, model_path, wav_path)
        validate_wav(wav_path)
        generated += 1

    _log(
        f"Done. generated={generated} skipped={skipped} "
        f"total={generated + skipped}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
